version: 2
updates:
  - package-ecosystem: 'docker'
    directory: '/.github'
    schedule:
      interval: 'daily'
    labels:
      - 'automerge'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    labels:
      - 'automerge'
  - package-ecosystem: 'pip'
    directory: '/'
    schedule:
      interval: 'daily'
    labels:
      - 'automerge'
