name: Check markdown links

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *' # Every month
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '.lycheeignore'
      - '.github/workflows/linkcheck.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linkcheck:
    env:
      DIR: 'docs'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Setup Julia
        uses: julia-actions/setup-julia@81d42b556a18b0d67455a742fcbffdeb49b3ffb0 # v2
      - name: Convert literate notebooks to markdown files
        shell: julia --color=yes {0}
        working-directory: ${{ env.DIR }}
        run: |
          import Pkg
          Pkg.add("Literate")
          using Literate
          for (root, dirs, files) in walkdir(pwd())
            for file in files
              if endswith(file, ".jl")
                nb = joinpath(root, file)
                Literate.markdown(nb, dirname(nb); mdstrings=true, flavor=Literate.CommonMarkFlavor())
              end
            end
          end
      - name: Setup Python
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5
        id: setup-python
        with:
          python-version: '3.x'
      - name: Cache python
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4
        id: cache-py
        with:
          key: ${{ runner.os }}-py-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('requirements.txt') }}
          path: ${{ env.pythonLocation }}
      - name: Install Python dependencies
        if: ${{ steps.cache-py.outputs.cache-hit != 'true' }}
        run: pip install -r requirements.txt
      - name: Convert ipynb files to markdown
        run: >
          find ${{ env.DIR }} -type f -name '*.ipynb' |
          parallel -j2 jupyter nbconvert --to markdown {}
      - name: Lychee cache
        id: restore-cache
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4
        with:
          save-always: 'true'
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-
      - name: Lychee link check
        uses: lycheeverse/lychee-action@2b973e86fc7b1f6b36a93795fe2c9c6ae1118621 # v1.10.0
        id: lychee
        with:
          fail: true
          args: --accept 200,204,429 --verbose --no-progress --cache --max-cache-age 1d "${{ env.DIR }}/**/*.md" "${{ env.DIR }}/**/*.qmd"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
